### ISSUE TITLE
Provide a field of view warning in Aspro2

### ISSUE THREAD

**Issue by jean-philippeberger** [JMMC-OpenDev/aspro#34]
## Description of the issue

To the best of my knowledge Aspro2 currently takes into account the "gaussian" field of view (fov) of the telescopes when a user or AMHRA model is used. The provided image is multiplied by the fov before the computation of interferometric observables. **This does not seem to be the case when the user selects an analytical model**. Therefore one can simulate an arbitrary wide object and have compute wrong observables because the telescope fov is not taken into account.

Although there are other factors that affect the field of view this one is particularly important.  The fiber causes a gaussian attenuation of the off-axis emission.  In the current Aspro2 implementation of the analytical functions this is not easy to handle. This issue recommends to at least warn the user that the defined model falls partly outside the telescope field of view.

## What should be checked

It is suggested to consider warning the user when any dimension of the object model is greater than approximately 0.2 x telescope fov . This corresponds to an attenuation of approximately 10%. The field of view is defined by a full-width at half maximum.

1) Upon entering of a new analytical model Aspro should check if any of the following model type parameters is > 0.2 x fov

| Model type | Parameter|
|---|---|
| Diam | diameter|
| elong_disk| minor_axis_diameter or minor_axis_diameter x elong_ratio|
|flatten_disk | major_axis_diameter x flatten_ratio or major_axis_diameter|
|circle|diameter|
|ring| diameter or diameter + width|
|elong_ring| minor_axis_diameter or minor_axis_diameter x elong_ratio|
|flatten_ring| major_internal_diameter x flatten_ratio or major_internal_diameter|

2) In addition there should be a check on all component pair separations i.e.

if any sep_ij > 0.2 x fov where sep_ij = sqrt((x_i - x_j)^2 + (y_i - y_j)^2)  is the distance between any two component types the object should be considered potentially altered by the object.

## Warning message

If any of the previous checks are positive

1- the warning status should include the following message: "The choosen model extension is potentially partly outside the telescope field of view"
2- Ideally, because the user do not always look at the warning the observable plots should include a warning. Possibilities: an overplotted text "Partly outside telescope field of view" or a different plot color transparency ?

**Comment by bourgesl** [comment]
Implemented, except 2 to be discussed or discarded.
